"use client";
import "./contact.css";
import {useEffect, useState} from "react";
import {PiBracketsSquareLight, PiChatCircleDots, PiCheckCircle, PiCircleThin, PiDotsNine, PiLineSegmentLight, PiPlusLight, PiPuzzlePiece, PiSparkleLight, PiTarget, PiUserCircle, PiWaveSineLight, PiWhatsappLogo} from "react-icons/pi";
import {LuBookOpen, LuBrainCircuit, LuChartNoAxesCombined, LuClipboardList, LuRoute, LuSprout} from "react-icons/lu";

const programs = [
  {n:"01",title:"Inglês",tag:"Por nível e objetivo",summary:"Comunicação, confiança e evolução contínua, com encontros de 60 minutos e material próprio.",paragraphs:["Aprender inglês não precisa ser uma sequência de palavras decoradas, exercícios repetitivos e medo de falar.","Na HSL, cada aluno aprende a partir do seu nível, dos seus objetivos e da forma como se desenvolve melhor. As aulas são planejadas para transformar o inglês em uma ferramenta de comunicação real, trabalhando compreensão, fala, leitura e escrita de maneira leve, contextualizada e progressiva.","Utilizamos materiais próprios, atividades dinâmicas e temas que se conectam à idade e aos interesses do aluno. Assim, ele participa mais, ganha confiança para se comunicar e consegue perceber a própria evolução.","Mais do que “saber a matéria”, queremos que o aluno se sinta capaz de usar o inglês."],practicalTitle:"Na prática, seu filho terá:",items:["Aulas individuais e personalizadas;","Encontros de 60 minutos;","Material próprio da HSL;","Acompanhamento contínuo da evolução;","Atividades adequadas ao nível, à idade e aos objetivos;","Um ambiente seguro para perguntar, tentar e aprender."],closing:"Conte para nós o que seu filho precisa. Vamos encontrar o melhor caminho para ele."},
  {n:"02",title:"Acompanhamento escolar",tag:"Organização e rotina",summary:"Apoio em tarefas, provas e estratégias de estudo para construir autonomia — sem criar dependência.",paragraphs:["Quando as tarefas viram motivo de estresse, as provas causam ansiedade e a criança parece não conseguir estudar sozinha, a dificuldade nem sempre está na falta de esforço.","Muitas vezes, ela precisa recuperar conteúdos que ficaram para trás, organizar melhor a rotina ou descobrir uma maneira de estudar que faça sentido para ela.","O acompanhamento escolar da HSL vai além de ajudar a terminar a tarefa. Trabalhamos as dificuldades apresentadas pela criança, retomamos conteúdos importantes e ensinamos estratégias para que ela compreenda, organize e realize suas atividades com cada vez mais segurança.","Nosso objetivo não é criar dependência. É construir autonomia para que, aos poucos, o aluno consiga estudar, interpretar comandos, resolver problemas e se preparar para as avaliações com mais confiança."],practicalTitle:"Na prática, seu filho terá:",items:["Apoio nas tarefas e nos conteúdos escolares;","Preparação e revisão para provas;","Identificação de dificuldades e lacunas de aprendizagem;","Estratégias de organização e estudo;","Explicações adaptadas à forma como ele aprende;","Incentivo à autonomia, sem respostas prontas."],closing:"A rotina escolar pode ficar mais organizada, produtiva e leve para toda a família."},
  {n:"03",title:"Psicopedagogia",tag:"Olhar especializado",summary:"Escuta cuidadosa, plano individual e orientação à família para compreender como a criança aprende.",paragraphs:["Quando uma dificuldade continua aparecendo, mesmo com explicações, reforço e esforço da família, é importante olhar além do conteúdo escolar.","Trocas de letras, dificuldade para ler, escrever, compreender comandos, manter a atenção ou organizar o pensamento não devem ser tratadas simplesmente como preguiça ou falta de interesse. Cada criança possui uma maneira própria de aprender — e entender esse processo é o primeiro passo para ajudá-la.","O acompanhamento psicopedagógico da HSL oferece uma escuta cuidadosa e um olhar individualizado sobre o desenvolvimento da aprendizagem. A partir das necessidades observadas, construímos um plano de intervenção com atividades e estratégias específicas, respeitando o ritmo e as características da criança.","A família também recebe orientações para compreender melhor as dificuldades e apoiar a criança de forma mais segura no dia a dia. Quando necessário, recomendamos a avaliação de outros profissionais para ampliar esse cuidado."],practicalTitle:"Na prática, o acompanhamento pode ajudar a:",items:["Compreender como a criança aprende;","Identificar barreiras no processo de aprendizagem;","Desenvolver atenção, memória, leitura, escrita e raciocínio;","Trabalhar organização e autonomia;","Fortalecer a confiança diante das atividades escolares;","Orientar a família sobre os próximos passos."],closing:"Antes de cobrar mais esforço, precisamos entender onde está a dificuldade."},
  {n:"04",title:"Combos HSL",tag:"Duas frentes, um cuidado",summary:"Inglês e acompanhamento escolar em uma agenda integrada, com economia e uma rotina mais leve.",paragraphs:["Algumas crianças precisam avançar no inglês e, ao mesmo tempo, de apoio para lidar melhor com a rotina e os conteúdos da escola. Para as famílias, conciliar diferentes horários, profissionais e pagamentos pode tornar a semana ainda mais cansativa.","Os Combos HSL reúnem inglês e acompanhamento escolar em uma agenda integrada, com condições especiais e uma rotina mais simples para a família.","Cada serviço mantém seu objetivo e seu planejamento, mas o cuidado com o aluno acontece de forma mais conectada. Conseguimos observar seu desenvolvimento com mais proximidade, adaptar estratégias e construir uma rotina que respeite suas necessidades."],practicalTitle:"Com o Combo HSL, sua família encontra:",items:["Inglês personalizado;","Acompanhamento de tarefas, conteúdos e provas;","Agenda integrada;","Planejamento de acordo com as necessidades do aluno;","Mais praticidade para a família;","Condição especial na contratação dos dois serviços."],closing:"Duas frentes de aprendizagem, um cuidado completo e uma rotina mais leve."},
];

const plans = [
  {category:"PSICOPEDAGOGIA",title:"Compreender para desenvolver",price:"R$ 210/sessão",benefits:[[LuBrainCircuit,"Compreensão das dificuldades de aprendizagem"],[LuRoute,"Estratégias personalizadas para aprender melhor"],[LuSprout,"Autonomia e confiança para aprender"]] as const},
  {category:"INGLÊS",title:"Confiança para se comunicar",price:"R$ 499/mês",priceNote:"Valores para planos trimestrais",benefits:[[LuClipboardList,"Plano personalizado"],[LuBookOpen,"Material próprio"],[LuChartNoAxesCombined,"Acompanhamento da evolução"]] as const},
  {category:"ACOMPANHAMENTO / REFORÇO",title:"Mais organização, menos sufoco",price:"R$ 559/mês",schoolColumns:[["Marista","Olimpo","Innova","Colégio Militar","Leonardo da Vinci","Único","Escola Canadense de Brasília"],["La Salle","Serius","Sigma","Colégio Militar dos Bombeiros","CIMAN","Maple Bear","Escolas Classe da Asa Sul"],["Salesiano","COC","Galois","Vitória Régia","Entre outras"]] as const},
];

const faqs = [
  ["Como funciona o primeiro contato?","Você nos conta quem será atendido, qual é a principal necessidade e quais objetivos espera alcançar. A partir disso, indicamos o serviço, a frequência e o formato mais adequados e verificamos os horários disponíveis antes da matrícula."],
  ["Os atendimentos são individuais?","Essa é a nossa modalidade principal, porque permite adaptar o ritmo, o conteúdo e as estratégias às necessidades de cada aluno. Duplas são avaliadas apenas quando há compatibilidade pedagógica, de faixa etária, série e horário — geralmente entre irmãos ou crianças da mesma escola."],
  ["Como funciona o ciclo trimestral?","Durante três meses, o aluno mantém o mesmo dia, horário e valor. Ao final do ciclo, a família decide se deseja renovar. O plano mensal também está disponível, mas depende da agenda e não reserva o horário para os meses seguintes."],
  ["Quem pode fazer atendimento presencial ou online?","Na unidade de Águas Claras, os atendimentos presenciais são voltados a crianças e adolescentes. Para adultos, o Inglês é oferecido online, com aulas individuais e personalizadas."],
  ["Qual é a diferença entre Acompanhamento Escolar e Psicopedagogia?","O Acompanhamento Escolar trabalha conteúdos, tarefas, provas e organização da rotina de estudos. A Psicopedagogia observa como o aluno aprende e desenvolve estratégias para dificuldades que persistem mesmo com apoio escolar. No primeiro contato, ajudamos a família a identificar qual serviço faz mais sentido."],
  ["Como funcionam os materiais utilizados?","No Inglês, utilizamos material próprio da HSL, adaptado ao nível e aos objetivos do aluno. No Acompanhamento Escolar, partimos dos livros, atividades e conteúdos da própria escola, complementando quando necessário. Na Psicopedagogia, os recursos são escolhidos de acordo com as necessidades observadas durante o processo."],
] as const;

export default function Home(){
  const [activePlan,setActivePlan]=useState(1);
  const [activeProgram,setActiveProgram]=useState<number|null>(null);
  const [contactName,setContactName]=useState("");
  const [contactPhone,setContactPhone]=useState("");
  const [contactProgram,setContactProgram]=useState("");
  const [contactSent,setContactSent]=useState(false);
  const formatPhone=(value:string)=>{
    const digits=value.replace(/\D/g,"").slice(0,11);
    if(digits.length<=2)return digits?`(${digits}`:"";
    if(digits.length<=6)return `(${digits.slice(0,2)}) ${digits.slice(2)}`;
    if(digits.length<=10)return `(${digits.slice(0,2)}) ${digits.slice(2,6)}-${digits.slice(6)}`;
    return `(${digits.slice(0,2)}) ${digits.slice(2,7)}-${digits.slice(7)}`;
  };
  const sendContact=(event:React.FormEvent<HTMLFormElement>)=>{
    event.preventDefault();
    if(!event.currentTarget.reportValidity())return;
    const message=encodeURIComponent(`Olá! Meu nome é ${contactName}. Tenho interesse em ${contactProgram} e gostaria de receber mais informações.`);
    setContactSent(true);
    window.open(`https://wa.me/5561999783314?text=${message}`,"_blank","noopener,noreferrer");
  };
  useEffect(()=>{const els=document.querySelectorAll("[data-reveal]"); const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("shown");io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[]);
  return <main>
    <header className="nav"><a className="brand" href="#inicio"><span className="brandmark">H</span><span>Home Sweet Learning<small>Águas Claras</small></span></a><nav aria-label="Navegação principal"><a href="#programas">Programas</a><a href="#planos">Planos</a></nav><a className="button small" href="#contato">Agendar conversa</a></header>

    <section id="inicio" className="hero">
      <div className="dots d1"/><div className="hero-copy" data-reveal>
        <h1>Seu filho não precisa estudar mais.<br/><em>Precisa encontrar o <span className="hero-underline">jeito certo<img src="/hsl-chalk-underline.png" alt="" aria-hidden="true"/></span> de aprender.</em></h1>
        <div className="actions"><a className="button" href="#contato">Quero conhecer a HSL <span>↗</span></a><a className="text-link" href="#programas">Explorar programas ↓</a></div>
        <div className="trust"><span><PiUserCircle className="trust-icon"/><b>Atendimento individual</b><small>por padrão</small></span><span><PiPuzzlePiece className="trust-icon icon-puzzle"/><b>Plano personalizado</b><small>para cada fase</small></span><span><PiChatCircleDots className="trust-icon icon-chat"/><b>Comunicação próxima</b><small>com a família</small></span></div>
      </div>
      <div className="hero-art hero-logo"><img src="/logo-hsl.png" alt="Home Sweet Learning"/><img className="hero-decor decor-tape" src="/hsl-user-tape.png" alt="" aria-hidden="true"/><img className="hero-decor decor-sparkle" src="/hsl-user-sparkle.png" alt="" aria-hidden="true"/><img className="hero-decor decor-arrow" src="/hsl-user-arrow.png" alt="" aria-hidden="true"/><img className="hero-decor decor-x" src="/hsl-user-x.png" alt="" aria-hidden="true"/><img className="hero-decor decor-label" src="/hsl-decor-label.png" alt="" aria-hidden="true"/></div>
      <div className="wave"/>
    </section>

    <section className="intro section" data-reveal><div className="split"><div className="intro-left"><div className="intro-kicker"><span className="kicker">UM NOVO JEITO DE ACOMPANHAR</span><img src="/hsl-user-x.png" alt="" aria-hidden="true"/></div><h2>Mais que aulas.<br/><em>Um caminho acompanhado.</em></h2></div><img className="intro-journey" src="/hsl-user-journey.png" alt="" aria-hidden="true"/><div className="intro-copy"><p className="lead">Na HSL, cada encontro faz parte de um programa com intenção: entendemos o momento da criança, organizamos o percurso e acompanhamos sua evolução.</p><p>Sem fórmulas prontas e sem aulas desconectadas. O vínculo, o material próprio e a conversa com a família transformam o aprendizado em uma experiência mais leve.</p></div></div></section>

    <section id="programas" className="programs section"><div className="section-head" data-reveal><div><span className="kicker">PROGRAMAS HSL</span><h2>O cuidado certo para<br/><em>cada necessidade.</em></h2></div><p>Serviços que funcionam de forma independente — ou juntos, em uma rotina integrada.</p></div><div className="program-grid service-list">{programs.map((p,i)=>{const isOpen=activeProgram===i;const panelId=`program-panel-${i}`;return <article className={`program service-row p${i+1}`} key={p.title} data-open={isOpen?"true":"false"} data-reveal><div className="service-row-head"><div className="service-heading"><span>{p.n}</span><div><h3>{p.title}</h3><small>{p.tag}</small></div></div><button className="service-more" type="button" aria-expanded={isOpen} aria-controls={panelId} onClick={()=>setActiveProgram(current=>current===i?null:i)}><span>{isOpen?"Fechar":"Saiba mais"}</span><b aria-hidden="true">{isOpen?"×":"+"}</b></button></div><div className="service-expand" id={panelId} aria-hidden={!isOpen}><div><div className="service-detail"><div className="service-copy">{p.paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><div className="service-practical"><h4>{p.practicalTitle}</h4><ul>{p.items.map(item=><li key={item}>{item}</li>)}</ul></div><p className="service-closing">{p.closing}</p></div></div></div></article>})}</div><div className="service-section-cta" data-reveal><h3>Vamos entender o que seu filho precisa?</h3><p>Conte para a nossa equipe quais são as dificuldades, os objetivos e a rotina da sua família. Vamos orientar você sobre o serviço mais adequado para este momento.</p><a className="button" href="mailto:homesweetlearningbr@gmail.com?subject=Quero conversar com a HSL Águas Claras">Conversar com a HSL</a></div></section>

    <section className="benefits section"><div className="benefits-title" data-reveal><span className="kicker">POR QUE A HSL?</span><h2><span className="benefit-small">Pequena no<br/>formato.</span><span className="benefit-large"><PiBracketsSquareLight className="care-bracket" aria-hidden="true"/><em>Grande no<br/>cuidado.</em></span></h2><div className="benefit-decor" aria-hidden="true"><PiCircleThin/><PiPlusLight/><PiWaveSineLight/><PiDotsNine/></div></div><div className="benefit-list"><PiSparkleLight className="benefit-sparkle" aria-hidden="true"/>{[["01","Atenção de verdade","Atendimento individual como padrão, respeitando ritmo e objetivos."],["02","Autonomia em construção","Apoio para a criança avançar com mais confiança, não depender do reforço."],["03","Família por perto","Comunicação humana, regras claras e acompanhamento contínuo."],["04","Rotina que cabe na vida","Horário reservado no ciclo e opções integradas para simplificar a semana."],["05","Escutamos","Conhecemos a criança, a família e o momento escolar."],["06","Planejamos","Definimos objetivos e uma rotina compatível com as necessidades reais."],["07","Acompanhamos","Observamos a evolução e ajustamos o percurso com clareza."]].map(x=><article key={x[0]} data-reveal><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}<PiLineSegmentLight className="benefit-slash" aria-hidden="true"/></div></section>

    <section id="planos" className="plans section"><div className="plans-shell"><div className="plans-head" data-reveal><span className="kicker">INVESTIMENTO</span><h2>Escolha o ritmo.<br/><em>Nós cuidamos do caminho.</em></h2><p>Ciclos trimestrais reservam vaga e horário. Também há opções mensais flexíveis, conforme disponibilidade.</p><PiSparkleLight className="plans-sparkle" aria-hidden="true"/></div><div className="plan-tabs-wrap" data-reveal>
      <div className="plan-tabs" role="tablist" aria-label="Programas HSL">{plans.map((plan,index)=><button id={`plan-tab-${index}`} key={plan.category} type="button" role="tab" aria-selected={activePlan===index} aria-controls="plan-tab-panel" tabIndex={activePlan===index?0:-1} className={activePlan===index?"is-active":""} onClick={()=>setActivePlan(index)} onKeyDown={event=>{if(event.key==="ArrowLeft"||event.key==="ArrowRight"){event.preventDefault();const direction=event.key==="ArrowRight"?1:-1;const next=(index+direction+plans.length)%plans.length;setActivePlan(next);requestAnimationFrame(()=>document.getElementById(`plan-tab-${next}`)?.focus())}}}>{plan.category}</button>)}</div>
      {(()=>{const plan=plans[activePlan];const benefits="benefits" in plan?plan.benefits:undefined;const schoolColumns="schoolColumns" in plan?plan.schoolColumns:undefined;return <article id="plan-tab-panel" className={`plan-tab-panel ${benefits?"has-benefits":""} ${schoolColumns?"has-schools":""}`} role="tabpanel" aria-labelledby={`plan-tab-${activePlan}`} key={plan.category}>
        <div className="plan-main"><span className="price-category">{plan.category}</span><h3>{plan.title}</h3><div className="plan-price"><span>A partir de</span><strong>{plan.price}</strong></div>{"priceNote" in plan&&plan.priceNote?<p className="plan-price-note">{plan.priceNote}</p>:null}</div>
        {benefits?<div className="plan-benefits" aria-label="Benefícios do plano">{benefits.map(([Icon,label])=><div key={label}><span className="plan-benefit-icon"><Icon aria-hidden="true"/></span><strong>{label}</strong></div>)}</div>:null}
        {schoolColumns?<div className="plan-schools" aria-label="Referências escolares dos alunos atendidos"><h4>Alunos que acompanhamos estudam em escolas como:</h4><div className="school-columns" role="list">{schoolColumns.map((column,columnIndex)=><div className="school-column" key={columnIndex}>{column.map(school=><div className={`school-item ${school.length>22?"is-long":""}`} role="listitem" key={school}><PiSparkleLight aria-hidden="true"/><span>{school}</span>{school==="Entre outras"?<PiWaveSineLight className="school-wave" aria-hidden="true"/>:null}</div>)}</div>)}</div><p>Instituições citadas como referência escolar dos alunos atendidos, sem vínculo institucional com a HSL.</p></div>:null}
      </article>})()}
      <a className="button orange plans-general-cta" href="#contato">Quero conversar sobre os programas ↗</a>
      <div className="combo-price-note" role="note" aria-label="Informações sobre Combos HSL">
        <div className="combo-summary"><span className="kicker">COMBOS HSL · INGLÊS + ACOMPANHAMENTO ESCOLAR</span><strong>A partir de <b>R$ 999/mês</b></strong><em>Valores para planos trimestrais</em><p>Duas frentes de aprendizado, uma agenda integrada e economia no ciclo.</p></div>
        <div className="combo-levels"><p><PiSparkleLight aria-hidden="true"/><b>Essencial</b><span>Inglês 1x + Acompanhamento 1x por semana</span></p><p><PiTarget aria-hidden="true"/><b>Foco Escolar</b><span>Inglês 1x + Acompanhamento 2x por semana</span></p><p><PiCheckCircle aria-hidden="true"/><b>Completo</b><span>Inglês 2x + Acompanhamento 2x por semana</span></p></div>
      </div>
    </div><p className="fine"><strong>Valores por criança. Atendimento individual.</strong> Matrícula única de R$ 150. Plano mensal flexível disponível sob consulta.</p></div></section>

    <section className="faq section"><div data-reveal><span className="kicker">DÚVIDAS FREQUENTES</span><h2>Antes de começar,<br/><em>vale saber.</em></h2></div><div className="faq-list">{faqs.map((x,i)=><details key={i} data-reveal><summary>{x[0]}<span aria-hidden="true">+</span></summary><p>{x[1]}</p></details>)}</div></section>

    <section id="contato" className="contact"><div className="contact-panel"><div className="contact-copy" data-reveal><span className="kicker light">VAMOS CONVERSAR?</span><h2>O próximo passo<br/>pode ser <em>mais leve.</em></h2><p>Fale com a gente pelo WhatsApp ou deixe seus dados. Primeiro entendemos; depois indicamos o melhor caminho.</p><a className="button orange contact-whatsapp" href="https://wa.me/5561999783314" target="_blank" rel="noreferrer"><span className="contact-icon"><PiWhatsappLogo aria-hidden="true"/></span>Conversar pelo WhatsApp <b aria-hidden="true">↗</b></a><div className="contact-meta"><a href="mailto:homesweetlearningbr@gmail.com">homesweetlearningbr@gmail.com</a><span>Rua Babaçu, lote 21, sala 406 · Águas Claras, DF</span></div><div className="contact-dots" aria-hidden="true"/></div><div className="contact-curve" aria-hidden="true"/><div className="contact-form-wrap" data-reveal><PiSparkleLight className="contact-sparkle" aria-hidden="true"/><form id="contact-form" className="contact-card" onSubmit={sendContact}><span>SE PREFERIR, ESCREVA</span><h3>Diga só o essencial.</h3><label>NOME<input required autoComplete="name" value={contactName} onChange={event=>{setContactName(event.target.value);setContactSent(false)}} placeholder="Digite seu nome"/></label><label>WHATSAPP<input required type="tel" inputMode="tel" autoComplete="tel" minLength={14} value={contactPhone} onChange={event=>{setContactPhone(formatPhone(event.target.value));setContactSent(false)}} placeholder="Digite seu WhatsApp"/></label><label>COMO PODEMOS AJUDAR?<select required value={contactProgram} onChange={event=>{setContactProgram(event.target.value);setContactSent(false)}}><option value="" disabled>Escolha um programa</option><option>Inglês</option><option>Acompanhamento / Reforço Escolar</option><option>Psicopedagogia</option><option>Combos</option><option>Ainda não sei</option></select></label><button className="contact-submit" type="submit">Enviar contato <span aria-hidden="true">→</span></button><p className="contact-followup" role={contactSent?"status":undefined}>{contactSent?"Tudo certo! Abrimos o WhatsApp com sua mensagem pronta.":"A gente continua a conversa com você."}</p></form></div></div></section>
    <footer><a className="brand" href="#inicio"><span className="brandmark">H</span><span>Home Sweet Learning<small>Águas Claras</small></span></a><p>Inglês · Acompanhamento Escolar · Psicopedagogia</p><a href="#inicio">Voltar ao topo ↑</a></footer>
  </main>
}
