"use client";
import {useEffect, useRef, useState} from "react";
import {PiArrowLeft, PiArrowRight, PiBookOpenText, PiBracketsSquareLight, PiCalendarCheck, PiChartLineUp, PiChatCircleDots, PiCircleThin, PiClipboardText, PiDotsNine, PiHandTap, PiLineSegmentLight, PiListChecks, PiNotebook, PiPlusLight, PiPuzzlePiece, PiSparkleLight, PiUserCircle, PiUsersThree, PiWaveSineLight} from "react-icons/pi";

const programs = [
  {n:"01",title:"Inglês",tag:"Por nível e objetivo",summary:"Comunicação, confiança e evolução contínua, com encontros de 60 minutos e material próprio.",paragraphs:["Aprender inglês não precisa ser uma sequência de palavras decoradas, exercícios repetitivos e medo de falar.","Na HSL, cada aluno aprende a partir do seu nível, dos seus objetivos e da forma como se desenvolve melhor. As aulas são planejadas para transformar o inglês em uma ferramenta de comunicação real, trabalhando compreensão, fala, leitura e escrita de maneira leve, contextualizada e progressiva.","Utilizamos materiais próprios, atividades dinâmicas e temas que se conectam à idade e aos interesses do aluno. Assim, ele participa mais, ganha confiança para se comunicar e consegue perceber a própria evolução.","Mais do que “saber a matéria”, queremos que o aluno se sinta capaz de usar o inglês."],practicalTitle:"Na prática, seu filho terá:",items:["Aulas individuais e personalizadas;","Encontros de 60 minutos;","Material próprio da HSL;","Acompanhamento contínuo da evolução;","Atividades adequadas ao nível, à idade e aos objetivos;","Um ambiente seguro para perguntar, tentar e aprender."],closing:"Conte para nós o que seu filho precisa. Vamos encontrar o melhor caminho para ele."},
  {n:"02",title:"Acompanhamento escolar",tag:"Organização e rotina",summary:"Apoio em tarefas, provas e estratégias de estudo para construir autonomia — sem criar dependência.",paragraphs:["Quando as tarefas viram motivo de estresse, as provas causam ansiedade e a criança parece não conseguir estudar sozinha, a dificuldade nem sempre está na falta de esforço.","Muitas vezes, ela precisa recuperar conteúdos que ficaram para trás, organizar melhor a rotina ou descobrir uma maneira de estudar que faça sentido para ela.","O acompanhamento escolar da HSL vai além de ajudar a terminar a tarefa. Trabalhamos as dificuldades apresentadas pela criança, retomamos conteúdos importantes e ensinamos estratégias para que ela compreenda, organize e realize suas atividades com cada vez mais segurança.","Nosso objetivo não é criar dependência. É construir autonomia para que, aos poucos, o aluno consiga estudar, interpretar comandos, resolver problemas e se preparar para as avaliações com mais confiança."],practicalTitle:"Na prática, seu filho terá:",items:["Apoio nas tarefas e nos conteúdos escolares;","Preparação e revisão para provas;","Identificação de dificuldades e lacunas de aprendizagem;","Estratégias de organização e estudo;","Explicações adaptadas à forma como ele aprende;","Incentivo à autonomia, sem respostas prontas."],closing:"A rotina escolar pode ficar mais organizada, produtiva e leve para toda a família."},
  {n:"03",title:"Psicopedagogia",tag:"Olhar especializado",summary:"Escuta cuidadosa, plano individual e orientação à família para compreender como a criança aprende.",paragraphs:["Quando uma dificuldade continua aparecendo, mesmo com explicações, reforço e esforço da família, é importante olhar além do conteúdo escolar.","Trocas de letras, dificuldade para ler, escrever, compreender comandos, manter a atenção ou organizar o pensamento não devem ser tratadas simplesmente como preguiça ou falta de interesse. Cada criança possui uma maneira própria de aprender — e entender esse processo é o primeiro passo para ajudá-la.","O acompanhamento psicopedagógico da HSL oferece uma escuta cuidadosa e um olhar individualizado sobre o desenvolvimento da aprendizagem. A partir das necessidades observadas, construímos um plano de intervenção com atividades e estratégias específicas, respeitando o ritmo e as características da criança.","A família também recebe orientações para compreender melhor as dificuldades e apoiar a criança de forma mais segura no dia a dia. Quando necessário, recomendamos a avaliação de outros profissionais para ampliar esse cuidado."],practicalTitle:"Na prática, o acompanhamento pode ajudar a:",items:["Compreender como a criança aprende;","Identificar barreiras no processo de aprendizagem;","Desenvolver atenção, memória, leitura, escrita e raciocínio;","Trabalhar organização e autonomia;","Fortalecer a confiança diante das atividades escolares;","Orientar a família sobre os próximos passos."],closing:"Antes de cobrar mais esforço, precisamos entender onde está a dificuldade."},
  {n:"04",title:"Combos HSL",tag:"Duas frentes, um cuidado",summary:"Inglês e acompanhamento escolar em uma agenda integrada, com economia e uma rotina mais leve.",paragraphs:["Algumas crianças precisam avançar no inglês e, ao mesmo tempo, de apoio para lidar melhor com a rotina e os conteúdos da escola. Para as famílias, conciliar diferentes horários, profissionais e pagamentos pode tornar a semana ainda mais cansativa.","Os Combos HSL reúnem inglês e acompanhamento escolar em uma agenda integrada, com condições especiais e uma rotina mais simples para a família.","Cada serviço mantém seu objetivo e seu planejamento, mas o cuidado com o aluno acontece de forma mais conectada. Conseguimos observar seu desenvolvimento com mais proximidade, adaptar estratégias e construir uma rotina que respeite suas necessidades."],practicalTitle:"Com o Combo HSL, sua família encontra:",items:["Inglês personalizado;","Acompanhamento de tarefas, conteúdos e provas;","Agenda integrada;","Planejamento de acordo com as necessidades do aluno;","Mais praticidade para a família;","Condição especial na contratação dos dois serviços."],closing:"Duas frentes de aprendizagem, um cuidado completo e uma rotina mais leve."},
];

const plans = [
  {category:"INGLÊS",title:"Confiança para se comunicar",prices:[["A partir de","","R$ 499/mês"]],starting:"R$ 499/mês",priceNote:"Valores para planos trimestrais",benefits:[[PiNotebook,"Plano personalizado"],[PiBookOpenText,"Material próprio"],[PiChartLineUp,"Acompanhamento da evolução"]]},
  {category:"ACOMPANHAMENTO / REFORÇO",title:"Mais organização, menos sufoco",prices:[["A partir de","","R$ 559/mês"]],starting:"R$ 559/mês",priceNote:"Valores para planos trimestrais",benefits:[[PiUserCircle,"Apoio individual"],[PiCalendarCheck,"Organização da rotina"],[PiListChecks,"Estratégias para provas e tarefas"]]},
  {category:"PSICOPEDAGOGIA",title:"Compreender para desenvolver",prices:[["A partir de","","R$ 210/sessão"]],starting:"R$ 210/sessão",priceNote:"Pacote de 10 sessões · válido por até 3 meses",benefits:[[PiUserCircle,"Atendimento individual"],[PiClipboardText,"Plano de intervenção"],[PiUsersThree,"Devolutivas para a família"]]},
];

export default function Home(){
  const [activePlan,setActivePlan]=useState(0);
  const [activeProgram,setActiveProgram]=useState<number|null>(null);
  const dragStart=useRef<number|null>(null);
  const showPrevious=()=>setActivePlan(current=>(current+plans.length-1)%plans.length);
  const showNext=()=>setActivePlan(current=>(current+1)%plans.length);
  useEffect(()=>{const els=document.querySelectorAll("[data-reveal]"); const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("shown");io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[]);
  return <main>
    <header className="nav"><a className="brand" href="#inicio"><span className="brandmark">H</span><span>Home Sweet Learning<small>Águas Claras</small></span></a><nav aria-label="Navegação principal"><a href="#programas">Programas</a><a href="#planos">Planos</a></nav><a className="button small" href="#contato">Agendar conversa</a></header>

    <section id="inicio" className="hero">
      <div className="dots d1"/><div className="hero-copy" data-reveal>
        <h1>Seu filho não precisa estudar mais.<br/><em>Precisa encontrar o <span className="hero-underline">jeito certo<img src="/hsl-chalk-underline.png" alt="" aria-hidden="true"/></span> de aprender.</em></h1>
        <div className="actions"><a className="button" href="#contato">Quero conhecer a HSL <span>↗</span></a><a className="text-link" href="#programas">Explorar programas ↓</a></div>
        <div className="trust"><span><PiUserCircle className="trust-icon"/><b>Atendimento individual</b><small>por padrão</small></span><span><PiPuzzlePiece className="trust-icon icon-puzzle"/><b>Plano personalizado</b><small>para cada fase</small></span><span><PiChatCircleDots className="trust-icon icon-chat"/><b>Comunicação próxima</b><small>com a família</small></span></div>
      </div>
      <div className="hero-art hero-logo"><img src="/logo-hsl.png" alt="Home Sweet Learning"/><img className="hero-decor decor-tape" src="/hsl-user-tape.png" alt="" aria-hidden="true"/><img className="hero-decor decor-sparkle" src="/hsl-user-sparkle.png" alt="" aria-hidden="true"/><img className="hero-decor decor-arrow" src="/hsl-user-arrow.png" alt="" aria-hidden="true"/><img className="hero-decor decor-x" src="/hsl-user-x.png" alt="" aria-hidden="true"/><img className="hero-decor decor-label" src="/hsl-decor-label.png" alt="" aria-hidden="true"/></div>
      <div className="wave"/>
    </section>

    <section className="intro section" data-reveal><div className="intro-kicker"><span className="kicker">UM NOVO JEITO DE ACOMPANHAR</span><img src="/hsl-user-x.png" alt="" aria-hidden="true"/></div><div className="split"><h2>Mais que aulas.<br/><em>Um caminho acompanhado.</em></h2><img className="intro-journey" src="/hsl-user-journey.png" alt="" aria-hidden="true"/><div><p className="lead">Na HSL, cada encontro faz parte de um programa com intenção: entendemos o momento da criança, organizamos o percurso e acompanhamos sua evolução.</p><p>Sem fórmulas prontas e sem aulas desconectadas. O vínculo, o material próprio e a conversa com a família transformam o aprendizado em uma experiência mais leve.</p></div></div></section>

    <section id="programas" className="programs section"><div className="section-head" data-reveal><div><span className="kicker">PROGRAMAS HSL</span><h2>O cuidado certo para<br/><em>cada necessidade.</em></h2></div><p>Serviços que funcionam de forma independente — ou juntos, em uma rotina integrada.</p></div><div className="program-grid service-list">{programs.map((p,i)=>{const isOpen=activeProgram===i;const panelId=`program-panel-${i}`;return <article className={`program service-row p${i+1}`} key={p.title} data-open={isOpen?"true":"false"} data-reveal><div className="service-row-head"><div className="service-heading"><span>{p.n}</span><div><h3>{p.title}</h3><small>{p.tag}</small><p className="service-summary">{p.summary}</p></div></div><button className="service-more" type="button" aria-expanded={isOpen} aria-controls={panelId} onClick={()=>setActiveProgram(current=>current===i?null:i)}><span>{isOpen?"Fechar":"Saiba mais"}</span><b aria-hidden="true">{isOpen?"×":"+"}</b></button></div><div className="service-expand" id={panelId} aria-hidden={!isOpen}><div><div className="service-detail"><div className="service-copy">{p.paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><div className="service-practical"><h4>{p.practicalTitle}</h4><ul>{p.items.map(item=><li key={item}>{item}</li>)}</ul></div><p className="service-closing">{p.closing}</p></div></div></div></article>})}</div><div className="service-section-cta" data-reveal><h3>Vamos entender o que seu filho precisa?</h3><p>Conte para a nossa equipe quais são as dificuldades, os objetivos e a rotina da sua família. Vamos orientar você sobre o serviço mais adequado para este momento.</p><a className="button" href="mailto:homesweetlearningbr@gmail.com?subject=Quero conversar com a HSL Águas Claras">Conversar com a HSL</a></div></section>

    <section className="benefits section"><div className="benefits-title" data-reveal><span className="kicker">POR QUE A HSL?</span><h2><span className="benefit-small">Pequena no<br/>formato.</span><span className="benefit-large"><PiBracketsSquareLight className="care-bracket" aria-hidden="true"/><em>Grande no<br/>cuidado.</em></span></h2><div className="benefit-decor" aria-hidden="true"><PiCircleThin/><PiPlusLight/><PiWaveSineLight/><PiDotsNine/></div></div><div className="benefit-list"><PiSparkleLight className="benefit-sparkle" aria-hidden="true"/>{[["01","Atenção de verdade","Atendimento individual como padrão, respeitando ritmo e objetivos."],["02","Autonomia em construção","Apoio para a criança avançar com mais confiança, não depender do reforço."],["03","Família por perto","Comunicação humana, regras claras e acompanhamento contínuo."],["04","Rotina que cabe na vida","Horário reservado no ciclo e opções integradas para simplificar a semana."],["05","Escutamos","Conhecemos a criança, a família e o momento escolar."],["06","Planejamos","Definimos objetivos e uma rotina compatível com as necessidades reais."],["07","Acompanhamos","Observamos a evolução e ajustamos o percurso com clareza."]].map(x=><article key={x[0]} data-reveal><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}<PiLineSegmentLight className="benefit-slash" aria-hidden="true"/></div></section>

    <section id="planos" className="plans section"><div className="plans-head" data-reveal><span className="kicker">INVESTIMENTO</span><h2>Escolha o ritmo.<br/><em>Nós cuidamos do caminho.</em></h2><p>Ciclos trimestrais reservam vaga e horário. Também há opções mensais flexíveis, conforme disponibilidade.</p></div><div className="price-carousel" role="region" aria-label="Planos e investimentos" tabIndex={0} onKeyDown={event=>{if(event.key==="ArrowLeft"){event.preventDefault();showPrevious()}if(event.key==="ArrowRight"){event.preventDefault();showNext()}}} onPointerDown={event=>{if(!(event.target as HTMLElement).closest("button,a")){dragStart.current=event.clientX;event.currentTarget.setPointerCapture(event.pointerId)}}} onPointerUp={event=>{if(dragStart.current!==null){const distance=event.clientX-dragStart.current;if(Math.abs(distance)>45){distance>0?showPrevious():showNext()}dragStart.current=null}}}>
      <div className="price-stage">
        {plans.map((plan,index)=>{const state=index===activePlan?"is-active":index===(activePlan+plans.length-1)%plans.length?"is-prev":"is-next";return <article className={`price-card ${state}`} key={plan.category} aria-current={index===activePlan?"true":undefined} aria-label={`Plano ${plan.category}${index===activePlan?", em destaque":""}`} tabIndex={index===activePlan?-1:0} onClick={()=>index!==activePlan&&setActivePlan(index)} onKeyDown={event=>{if(index!==activePlan&&(event.key==="Enter"||event.key===" ")){event.preventDefault();setActivePlan(index)}}}>
          {index===activePlan?<><span className="price-category">{plan.category}</span><h3>{plan.title}</h3><div className="active-prices single-price">{plan.prices.map(([label,prefix,value])=><div key={label}><span>{label}</span><strong>{prefix&&<small>{prefix}</small>} {value}</strong></div>)}</div><p className="plan-price-note">{plan.priceNote}</p><div className="plan-benefits">{plan.benefits.map(([Icon,label])=><div key={label as string}><Icon aria-hidden="true"/><span>{label as string}</span></div>)}</div></>:<><span className="pill">{plan.category}</span><h3>{plan.title}</h3><div className="inactive-price"><span>A partir de</span><strong>{plan.starting}</strong></div><button type="button" onClick={event=>{event.stopPropagation();setActivePlan(index)}}>Ver plano</button></>}
        </article>})}
        <button className="price-nav price-prev" type="button" aria-label="Ver plano anterior" onClick={showPrevious}><PiArrowLeft aria-hidden="true"/></button><button className="price-nav price-next" type="button" aria-label="Ver próximo plano" onClick={showNext}><PiArrowRight aria-hidden="true"/></button>
      </div>
      <div className="price-dots" aria-label="Selecionar plano">{plans.map((plan,index)=><button key={plan.category} type="button" className={index===activePlan?"active":""} aria-label={`Selecionar ${plan.category}`} aria-current={index===activePlan?"true":undefined} onClick={()=>setActivePlan(index)}/>)}</div>
      <p className="carousel-hint"><PiHandTap aria-hidden="true"/> Clique, arraste ou use as setas</p>
      <a className="button orange plans-general-cta" href="#contato">Quero conversar sobre os programas ↗</a>
      <div className="combo-price-note" role="note" aria-label="Informações sobre Combos HSL">
        <div className="combo-summary"><span className="kicker">COMBOS HSL · INGLÊS + ACOMPANHAMENTO ESCOLAR</span><strong>A partir de <b>R$ 999/mês</b></strong><em>Valores para planos trimestrais</em><p>Duas frentes de aprendizado, uma agenda integrada e economia no ciclo.</p></div>
        <div className="combo-levels"><p><b>Essencial</b><span>Inglês 1x + Acompanhamento 1x por semana</span></p><p><b>Foco Escolar</b><span>Inglês 1x + Acompanhamento 2x por semana</span></p><p><b>Completo</b><span>Inglês 2x + Acompanhamento 2x por semana</span></p></div>
      </div>
    </div><p className="fine"><strong>Valores por criança. Atendimento individual.</strong> Matrícula única de R$ 150. Plano mensal flexível disponível sob consulta.</p></section>

    <section className="founding"><div data-reveal><span className="kicker light">LANÇAMENTO · 10 VAGAS</span><h2>Faça parte das<br/><em>Founding Families.</em></h2><p>As 10 primeiras famílias da HSL Águas Claras recebem isenção da matrícula no primeiro ciclo. Na Psicopedagogia, a triagem inicial também é gratuita na contratação do primeiro pacote.</p><a className="button orange" href="#contato">Quero saber se ainda há vagas ↗</a><small>Benefício limitado, pessoal e não cumulativo. Mensalidade paga normalmente desde o primeiro mês.</small></div><div className="big-ten" aria-hidden="true">10<span>famílias</span></div></section>

    <section className="faq section"><div data-reveal><span className="kicker">DÚVIDAS FREQUENTES</span><h2>Antes de começar,<br/><em>vale saber.</em></h2></div><div className="faq-list">{[["Como é o primeiro contato?","Conversamos sobre a necessidade da criança e orientamos o programa mais adequado antes da matrícula."],["Os atendimentos são em grupo?","O atendimento é individual por padrão. Duplas acontecem somente em casos pedagogicamente compatíveis, como irmãos gêmeos ou crianças da mesma escola, série e faixa etária."],["Qual a diferença do ciclo trimestral?","O ciclo reserva vaga e horário, protege o valor durante o período e dá acesso aos benefícios elegíveis. O mensal flexível depende da agenda."],["Existem combos?","Sim. Há três combinações de Inglês + Acompanhamento Escolar, com agenda integrada e economia em relação à contratação separada."]].map((x,i)=><details key={i} data-reveal><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div></section>

    <section id="contato" className="contact"><div className="contact-copy" data-reveal><span className="kicker light">VAMOS CONVERSAR?</span><h2>O próximo passo pode ser<br/><em>mais leve do que parece.</em></h2><p>Conte um pouco sobre a criança e o que vocês estão buscando. A HSL ajuda a encontrar o caminho mais adequado.</p><a className="button orange" href="mailto:homesweetlearningbr@gmail.com?subject=Quero conhecer a HSL Águas Claras">Agendar uma conversa ↗</a></div><div className="contact-card" data-reveal><span>HSL ÁGUAS CLARAS</span><h3>Aprender também<br/>pode ser acolhedor.</h3><a href="mailto:homesweetlearningbr@gmail.com">homesweetlearningbr@gmail.com</a><p>Atendimento presencial<br/>Águas Claras · Distrito Federal</p></div></section>
    <footer><a className="brand" href="#inicio"><span className="brandmark">H</span><span>Home Sweet Learning<small>Águas Claras</small></span></a><p>Inglês · Acompanhamento Escolar · Psicopedagogia</p><a href="#inicio">Voltar ao topo ↑</a></footer>
  </main>
}
